# Generated by Django 3.0.8 on 2020-07-28 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Studentdbs',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('score', models.DecimalField(decimal_places=2, max_digits=10)),
                ('age', models.DecimalField(decimal_places=2, max_digits=13)),
            ],
        ),
    ]
